### ISSUE TITLE
Element not moving with window resizing?

### ISSUE THREAD

**Issue by dandv** [HubSpot/tether#121]
I'm creating a Tether [like this](https://github.com/iDoRecall/selection-menu/blob/gh-pages/src/selection-menu.js#L242). In Chrome 44, when I resize the window, the element doesn't track the target.

The documentation [suggests](http://github.hubspot.com/tether/#element-moving) that Tether should automatically move the element when the window resizes. What am I doing wrong? Here is the [live demo](http://idorecall.github.io/selection-menu/demos/iDoRecall.html).

**Comment by TrevorBurnham** [comment]
The problem is that the `<span>` you've created as the target doesn't move on resize. Here's an example where I've selected the word "trigger" and then resized the window slightly, moving the word "trigger" but not the `<span>`:

![screen shot 2016-04-20 at 2 42 55 pm](https://cloud.githubusercontent.com/assets/224895/14686320/2d1597ea-0706-11e6-8a7c-fb8fa84403ec.png)

So the Tether is still correctly positioned relative to the target, it's just that the target isn't where you want it to be.

I would suggest that instead of positioning the `<span>` yourself, you create an inline `<span>` around the text that you want to have selected.
