### ISSUE TITLE
Meteor package?

### ISSUE THREAD

**Issue by cvrebert** [HubSpot/tether#153]
Would you be open to publishing an official [Meteor package](https://atmospherejs.com/) for Tether? It mostly involves adding a `package.js` file and setting up some GitHub webhooks. It doesn't add any extra steps to the process of shipping a new release. If you agree, we can probably find some Meteor community members to make a PR and guide you through setting up the webhooks, like they did for Bootstrap.

This would help us out over at Bootstrap (https://github.com/twbs/bootstrap/issues/19005), since currently we'd have to make Bootstrap v4's Meteor package depend on a third-party packaging of Tether (which is awkward since there are several of them, and we'd rather avoid debates over which to pick).

**Comment by bySabi** [comment]
This package [meteor-global-tether](https://github.com/orgztion/meteor-global-tether) expose Tether on Meteor global of browser and node.
Don´t install nothing. Just `import` already installed `tether` npm.

Is for `Meteor 1.3`, the incoming release with ES6 modules support.

Useful for everyone who want work with `tether` and `bootstrap` npm modules.

**Comment by cvrebert** [comment]
So, I'll take that as a "No" ?

**Comment by geekjuice** [comment]
I think it's fair to include the `package.js` to have it supported as an official meteor package. I'm going to guess this was closed because many of us have not worked closely with meteor and unfamiliar with the `package.js` structure.

@cvrebert Would you be willing to create pull request adding the `package.js`. Added bonus if you can make sure we are using `require('package')` anywhere which would collide with the `package.json`. 👍
