### ISSUE TITLE
Loading of an <img> in a Tethered element doesn't cause position recalculation?

### ISSUE THREAD

**Issue by cvrebert** [HubSpot/tether#181]
Refs https://github.com/twbs/bootstrap/issues/19981

Example: https://jsfiddle.net/bw2v2q6s/8/

Steps to reproduce:
1. Open https://jsfiddle.net/bw2v2q6s/8/show/ in Chrome.
2. Open DevTools.
3. Go to the Network tab.
4. Check the "Disable cache" button.
5. Instead of "No throttling", select "GPRS" (or some other very slow option).
6. Click the "What is a CVC?" button.
7. Observe that, once the image loads, the Drop is misplaced.
8. Observe that resizing the window triggers a position recalculation that correctly repositions the Drop.

Having merely searched through your code and not properly read through it, my wild speculation is that you need to add something like:
```js
// ...initializing the Tether instance...
var reposition = thisTether.position.bind(thisTether);
// Trigger repositioning when images, etc. within the tethered element load and thus resize themselves.
// Use the Capture Phase since neither of these events bubble.
element.addEventListener('progress', reposition, true);
element.addEventListener('load', reposition, true);
// ...
```

**Comment by TrevorBurnham** [comment]
That's correct: Tether only listens for `resize` and `scroll` events. It does not detect changes to the Tethered element's size due to, in your example, image loads. Unfortunately, `'load'` events do not bubble, so there is no way to even attach listeners for those events until the `<img>` elements exist.

There are a number of other ways that Tether elements can become detached from their target, notably DOM changes and animations/transitions. Trying to detect and respond to all of these is, unfortunately, impossible to do in a reasonably performant way. That's why Tether instances have a `position()` method. That allows you to add code to your application to reposition Tether in response to events other than `scroll` and `resize`. For example, after you've rendered all of your `<img>` nodes in the Tethered element:

```js
var images = tetheredElement.querySelectorAll('img');
[].forEach.call(images, function(image) {
  image.addEventListener('load', thisTether.position.bind(thisTether));
});
```

**Comment by cvrebert** [comment]
> Unfortunately, 'load' events do not bubble, so there is no way to even attach listeners for those events until the `<img>` elements exist.

Erm, can't you just use capture-phase event listeners instead of bubble-phase ones?

**Comment by TrevorBurnham** [comment]
Ah, you are correct. Still, handling such events is beyond the scope of what Tether does.
