### ISSUE TITLE
Add option to force rounding of placement

### ISSUE THREAD

**Issue by jeremyk** [HubSpot/tether#296]
I see in the code it checks for a retina display and then rounds if one is not found. On my screen it is not rounding (which should be good as it is the LG 5K ultrawide) but the text comes out blurry. I would propose an option be added to force rounding (rather than worry about why this is happening as I don't think sub pixel positioning really matters for my use case).

I am attaching screenshots where there is a popup I am positioning with tether. In one of them I manually round via the inspector and you can see the text is much clearer.

<img width="123" alt="not rounded" src="https://user-images.githubusercontent.com/223474/51648283-b069e080-1f34-11e9-8366-287f059d5f9a.png">
<img width="124" alt="rounded" src="https://user-images.githubusercontent.com/223474/51648284-b069e080-1f34-11e9-9a0e-6ca2491ae74d.png">

**Comment by TrevorBurnham** [comment]
That's interesting. I haven't noticed any blurring with Tethers on my 5K display. Are you running it at 2560x1080 scaling (that is, exactly 2x2 physical pixels for each virtual pixel)? Also, what OS and browser is this in?

**Comment by jeremyk** [comment]
Running Mac OS 10.14. Native resolution as far as I can tell. Google Chrome 72 Beta.

<img width="637" alt="screen shot 2019-01-28 at 12 03 57 pm" src="https://user-images.githubusercontent.com/223474/51863024-d1478280-22f4-11e9-876a-a03b384b4793.png">

**Comment by TrevorBurnham** [comment]
Odd. I'm not sure why I haven't see this myself. Are you [disabling the GPU](http://tether.io/#gpu) by any chance?

If you really thing this is the solution, I'd accept a PR to add this option.

**Comment by jeremyk** [comment]
I am not disabling the GPU. And it is odd as I can’t figure out exactly why
this happens on the tether element and not a test DIV that I translate a
fractional amount of pixels. It is something specific to the way we are
using it so I am not surprised you haven’t seen it. I can spend a little
more time digging in sometime soon.

**Comment by TrevorBurnham** [comment]
@jeremyk I'm actually seeing this now. It looks like the blur is only noticeable if the `transform` values are about as far away from the physical pixel boundary as possible. So for instance, on a 5K display, `devicePixelRatio === 2` and the `transform` value that looks the worst is `translateX(0.75px) translateY(0.75px)`. Values that are closer to the nearest half-integer look OK, which is why I hadn't noticed this problem before.

I think a solution here is to generalize the rounding logic to "if `devicePixelRatio` is an exact integer, round the transform values to the nearest `1/devicePixelRatio`" so that it snaps to the nearest physical pixel and looks nice and crisp. For folks out there with a non-integer `devicePixelRatio`, things will have some blur no matter what we do. 🤷‍♂️ 

PRs welcome!
